-- CRIAÇÃO E ESCOLHA DO DATABASE 
CREATE DATABASE USUARIO;
USE USUARIO;

-- CRIAÇÃO DA TABELA DE CLIENTES
CREATE TABLE TB_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	PRIMEIRO_NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,    
	SEXO CHAR(1),
    ESTADO VARCHAR(30)
);

/*INSERT ATRAVÉS DE UM ARQUIVO TXT 
1- PASSEI O CAMINHO DO ARQUIVO TXT
2- SELECIONEI A TABELA DE INSERÇÃO
3- INFORMEI O TERMINO DE CADA REGISTRO E O MODO DE CERCO
4- INFORMEI QUE CADA LINHA DE DADOS TEM UMA QUBRA \n
5- SELECIONEI OS CAMPOS QUE SERÃO PREENCHIDO PELOS DADOS DO TXT
*/
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/clientes.txt'
INTO TABLE TB_CLIENTE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(PRIMEIRO_NOME,SOBRENOME,SEXO,ESTADO);


SELECT	PRIMEIRO_NOME,
		SOBRENOME,
        SEXO,
        ESTADO
FROM TT;