-- CRIAÇÃO E ESCOLHA DO DATABASE 
CREATE DATABASE USUARIO;
USE USUARIO;

-- CRIAÇÃO DA TABELA DE CLIENTES
CREATE TABLE TB_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	PRIMEIRO_NOME VARCHAR(30) NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL,    
	GENERO CHAR(1),
    CPF VARCHAR(14) UNIQUE,
    FKENDERECO INT,
    FKTELEFONE INT
);

INSERT INTO TB_CLIENTE(PRIMEIRO_NOME,SOBRENOME,GENERO,CPF,FKENDERECO)
VALUES ('MATHEUS','CARDOSO','M','123.456.789-10',1);

INSERT INTO TB_ENDERECO (ESTADO,UF,CIDADE,BAIRRO,RUA,NUMERO)
VALUES('MINAS GERAIS','MG','BELO HORIZONTE','TQ','ST. JOANA','20');


-- CRIAÇÃO DA TABELA DE ENDERECOS
CREATE TABLE TB_ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO VARCHAR(30) NOT NULL,
    UF CHAR(2),
    CIDADE VARCHAR(20),
    BAIRRO VARCHAR(30),
    RUA VARCHAR(30),
    NUMERO VARCHAR(5)
);

-- CRIAÇÃO DA TABELA DE TELEFONES
CREATE TABLE TB_TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL','COM'),
    DDD CHAR(2),
	TELEFONE VARCHAR(9)
);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY (FKENDERECO)
REFERENCES TB_ENDERECO(IDENDERECO);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (FKTELEFONE)
REFERENCES TB_TELEFONE(IDTELEFONE);





DROP TABLE TB_CLIENTE;
DROP TABLE TB_TELEFONE;
DROP TABLE TB_ENDERECO;


/*INSERT ATRAVÉS DE UM ARQUIVO TXT 
1- PASSEI O CAMINHO DO ARQUIVO TXT
2- SELECIONEI A TABELA DE INSERÇÃO
3- INFORMEI O TERMINO DE CADA REGISTRO E O MODO DE CERCO
4- INFORMEI QUE CADA LINHA DE DADOS TEM UMA QUBRA \n
5- SELECIONEI OS CAMPOS QUE SERÃO PREENCHIDO PELOS DADOS DO TXT
*/
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/clientes.txt'
INTO TABLE TB_CLIENTE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(PRIMEIRO_NOME,SOBRENOME,SEXO,ESTADO);


SELECT	PRIMEIRO_NOME,
		SOBRENOME,
        SEXO,
        ESTADO
FROM TT;


DELETE FROM TB_ENDERECO
WHERE IDENDERECO = 1;

DELETE FROM TB_CLIENTE
WHERE IDCLIENTE = 2;


select * FROM TB_CLIENTE;
select * FROM TB_ENDERECO;